def _build_batch_corr_df(
    self,
    iter_idx: int,
    d_targets: dict,
    dR_gray: np.ndarray,
    dG_gray: np.ndarray,
    dB_gray: np.ndarray,
    corr_flag: np.ndarray,
    mapLUT: np.ndarray,
    RH0: np.ndarray, GH0: np.ndarray, BH0: np.ndarray,
    RH:  np.ndarray, GH:  np.ndarray, BH:  np.ndarray,
    wCx_gray: np.ndarray,
    wCy_gray: np.ndarray,
    wG_gray:  np.ndarray,
):